spring.application.name=Issue-Dashboard
server.port=8890

spring.data.mongodb.uri=mongodb://localhost:27017/issue_dashboard
spring.data.mongodb.database=issue_dashboard

# SharePoint Configuration
sharepoint.siteUrl=https://gdncomm.sharepoint.com/sites/InventoryPlanning
sharepoint.listName=Issue Dashboard
sharepoint.fieldName=MessageText
sharepoint.username=pranav.garg@gdn-commerce.com
sharepoint.password=WaterBottle@2001

# HTTP Client Configuration
spring.webflux.timeout.connect=30s
spring.webflux.timeout.read=30s
spring.webflux.timeout.write=30s

# Gemini Configuration
gemini-client-api-key=AIzaSyCXQp-9lrqfOHCPoqC7oLg8IbsrEFzeeac
gemini-client-api-url=${GEMINI_CLIENT_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}