spring.application.name=Issue-Dashboard
server.port=8888

spring.data.mongodb.uri=mongodb://localhost:27017/issue_dashboard
spring.data.mongodb.database=issue_dashboard

# Gemini Configuration
gemini-client-api-key=AIzaSyCXQp-9lrqfOHCPoqC7oLg8IbsrEFzeeac
gemini-client-api-url=${GEMINI_CLIENT_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}