spring.application.name=Issue-Dashboard
server.port=8890

spring.data.mongodb.uri=mongodb://localhost:27017/issue_dashboard
spring.data.mongodb.database=issue_dashboard

# SharePoint Configuration
sharepoint.siteUrl=https://gdncomm.sharepoint.com/sites/InventoryPlanning
sharepoint.listName=Issue Dashboard
sharepoint.fieldName=MessageText
sharepoint.username=pranav.garg@gdn-commerce.com
sharepoint.password=WaterBottle@2001

# HTTP Client Configuration
spring.webflux.timeout.connect=30s
spring.webflux.timeout.read=30s
spring.webflux.timeout.write=30s